# Data paths
local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/temp
#local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/wifi-csi-2gb-dataset

file_name_for_gait = *C03*.csv
output_path = /Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/experiments
experiment_name = 1_EPOCHS_HYPERPARAMS_test
 
log_level=DEBUG

# Standardised Hyperparameters -  used for model training

learning_rate = 1, 2, 4
batch_size  = 256, 512, 1024
optimizer = adam, adamw, sgd
weight_decay = 0, 1e-5, 1e-3
epochs = 1  


#learning_rate = 0.0001, 0.00005
#batch_size = 16, 32, 64
#optimizer = adam, adamw, sgd
#weight_decay = 0, 1e-5, 1e-3
#epochs = 100



 