# Data paths
#local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/temp
local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/wifi-csi-2gb-dataset

file_name_for_gait = *C03*.csv
output_path = /Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/experiments
experiment_name = 100_EPOCHS_HYPERPARAMS_SET_2
 
log_level=DEBUG

# Standardised Hyperparameters -  used for model training

learning_rate = 0.001, 0.0005
batch_size  = 16
optimizer = adam
weight_decay = 1e-4
epochs = 100


#learning_rate = 0.002
#batch_size  = 32
#optimizer = adam
#weight_decay = 1e-4
#epochs = 1



 