# Data paths
#local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/temp
#local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/wifi-csi-2gb-dataset
local_data_path=/Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/DATASET/wifi-csi-2gb-dataset_C03

file_name_for_gait = *C03*.csv
output_path = /Users/sanjeev/VNIT/FINAL_PRJ_PHASE2/experiments
experiment_name = 100_EPOCHS_DenseNet1D_TEST_1.5
 
log_level=DEBUG

# Standardised Hyperparameters -  used for model training

#learning_rate = 1, 2, 4
#batch_size  = 256, 512, 1024
#optimizer = adam, adamw, sgd
#weight_decay = 0, 1e-5, 1e-3
#epochs = 1 

# training_model_list = CSILSTMNet, DenseNet1D, EfficientNet1DLSTM, MobileNetV3_1D_LSTM
training_model_list = DenseNet1D

learning_rate = 0.0001, 0.0005
batch_size =  64, 32
optimizer = adam
weight_decay = 1e-5
epochs =100

t_shuffle = True
v_shuffle = False

window = 128
stride = 64

#learning_rate = 0.0002
#batch_size = 16
#optimizer = adam
#weight_decay = 0 
#epochs = 5



 